pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }

    environment { 
        COURSE = 'Jenkins'
    }

    options {
        timeout(time: 1, unit: 'HOURS') 
        disableConcurrentBuilds()
    }


    stages {
        stage('terraform init') {
            steps {
                script {
                    sh """
                        echo "Initializing Terraform... scripted shell command"
                        terraform init
                    """
                }
            }
        }
        stage('terraform plan') {
            steps {
                script {
                    sh """
                        echo "Planning Terraform changes... scripted shell command"
                        terraform plan
                    """
                }
            }
        }
        stage('terraform apply') {
            steps {
                script {
                    sh """
                        echo "Applying Terraform changes... scripted shell command"
                        terraform apply -auto-approve
                    """
                }
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success{
            echo "Build and Test completed successfully!"
        }
        failure{
            echo "Build or Test failed!"
        }
        aborted{
            echo "Build or Test aborted!"
        }
    }
}