pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }

    environment { 
        COURSE = 'Jenkins'
    }

    options {
        timeout(time: 1, unit: 'HOURS') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }


    stages {
        stage('terraform init') {
            steps {
                withAWS(region:'us-east-1',credentials:'aws-creds'){
                script {
                    sh """
                        cd 10-sg
                        echo "Initializing Terraform... scripted shell command"
                        terraform init
                    """
                }
                }
            }
        }
        stage('terraform plan') {
            steps {
                withAWS(region:'us-east-1',credentials:'aws-creds'){
                script {
                    sh """
                        cd 10-sg
                        echo "Planning Terraform changes... scripted shell command"
                        terraform plan
                    """
                    }
                }
            }
        }
        stage('terraform apply') {
            steps {
                withAWS(region:'us-east-1',credentials:'aws-creds'){
                script {
                    sh """
                        cd 10-sg
                        echo "Applying Terraform changes... scripted shell command"
                        terraform apply -auto-approve
                    """
                }
                }
            }
        }

        stage ("parallel trigger") {
            parallel {
                stage('bastion') {
                    steps {
                        script {

                                build job: '20-bastion',
                                wait: false,
                                propagate: false
                            
                        }
                        
                    }
                }

                stage('sg-rules') {
                    steps {
                        script {
                            
                                build job: '30-sg-rules',
                                wait: false,
                                propagate: false
                            
                        }
                        
                    }
                }

                stage('ecr') {
                    steps {
                        script {
                            
                                build job: '40-ecr',
                                wait: false,
                                propagate: false
                            
                        }
                        
                    }
                }

                stage('acm') {
                    steps {
                        script {
                            
                                build job: '70-acm',
                                wait: false,
                                propagate: false
                            
                        }
                    }
                }
                stage('eks') {
                    steps {
                        script {
                            
                                build job: '90-eks',
                                wait: false,
                                propagate: false
                            
                        }
                    }
                }
            }
        }

        stage('ALB') {
            stage('bastion') {
                    steps {
                        script {
                            
                                build job: '80-frontendalb',
                                wait: false,
                                propagate: false
                            
                        }
                        
                    }
                }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success{
            echo "Build and Test completed successfully!"
        }
        failure{
            echo "Build or Test failed!"
        }
        aborted{
            echo "Build or Test aborted!"
        }
    }
}